// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLbFoBnVqd3fxmxCAegEzMzKAaAu061hc',
    appId: '1:935176624070:web:067a90c16171b20f8e44c7',
    messagingSenderId: '935176624070',
    projectId: 'azure-notification77576576',
    authDomain: 'azure-notification77576576.firebaseapp.com',
    storageBucket: 'azure-notification77576576.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBacoMGQiNZMDJOrizVSaPWoT2h3Q0kovo',
    appId: '1:935176624070:android:0fa283df106aac118e44c7',
    messagingSenderId: '935176624070',
    projectId: 'azure-notification77576576',
    storageBucket: 'azure-notification77576576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIFTFJZBaTOuR6rL8bhG0lu1XBtttkFsM',
    appId: '1:935176624070:ios:ee4a2b083c757e548e44c7',
    messagingSenderId: '935176624070',
    projectId: 'azure-notification77576576',
    storageBucket: 'azure-notification77576576.appspot.com',
    iosClientId: '935176624070-a4b84rr6vnmicpres3l33o39628s42f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.azurepush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIFTFJZBaTOuR6rL8bhG0lu1XBtttkFsM',
    appId: '1:935176624070:ios:ee4a2b083c757e548e44c7',
    messagingSenderId: '935176624070',
    projectId: 'azure-notification77576576',
    storageBucket: 'azure-notification77576576.appspot.com',
    iosClientId: '935176624070-a4b84rr6vnmicpres3l33o39628s42f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.azurepush',
  );
}
